const RecipesData = [
    {
        title: "Steak Fried Rice",
        _id: 1,
        imageUrl: "../../src/photos/Recipe-Photos/steakFriedRice.jpg",
        src: "/steakFriedRice",

        methods: ["Sous Vide", "Saute"],
        categories: ["Dinner", "Steak", "Rice"],
        time: "1 hr",
        ingredients: [
            "1.5 Cup Leftover Rice",
            "1 Flank Steak",
            "1 cup Peppers",
            "1 cup Onions",
            ".5 cup Carrots",
            ".5 cup Baby Corns",
            "2 sprigs or 2 tsp dried Rosemary",
        ],
        instructions: [
            "First, the rice. Add oil to a small pot and place over low heat. Add 1 tbsp of butter, rosemary and other aromatics and allow to sauté for 3 minutes. Add 2 cups of chicken broth to the pot and bring to a boil. Next add in your 1.5 cups of washed jasmine rice. Stir as you bring it back to a boil. Then place a lid on the rice and drop the heat to a low simmer. Simmer rice for 13-15 minutes, and do not lift the lid. Once the rice seems to have absorbed our chicken broth: pull from heat, lift the lid, and stir. Allow it to rest until cools and place in fridge. You should cook the fried rice the next day, but if you want, you can chill it for as little as 30 minutes.",
            "Next, we cook the steak. I typically use a flank steak. First cut your steak into small slices marinade steak for 30 minutes to 24 hours in desired spice mix along with some teriyaki sauce. Bring a wok over 7/10 heat and place oil in your pan. You will be using the same wok the whole time, so do not wash out the yummy bits. Quickly sauté your strips being sure not to overcrowd the pan (this may take several batches). When finished, dice the steak to desired size for a rice dish, and set aside.",

            "Next, we prep the veggies. First dice the veggies into desired shape. Place the peppers and onions separate from the corn and carrots. Place a small amount of oil in the same wok over medium-high heat and add in the carrots and corn. Cover this and occasionally flick the wok to move the veggies around. You may need to scrape some of the steak fond to incorporate it into your veggies. After 2 minutes, add in the onions and peppers and remove the cover. Cook to desired crunch level and place the veggies aside.",

            "Finally, we are ready to combine everything. Make sure you have some soy sauce and the teriyaki  sauce you used for the marinade. First, we bring our wok back up to high heat(9/10) with some oil. Add rice to wok and break up the clumps, stirring and flicking the wok as you go to make sure no rice burns. Once that is done, add veggies into the wok and incorporate. Begin adding some soy sauce and teriyaki sauce to taste. Once you have a desired salt and flavor level, add in your diced steak and incorporate once more. Finally, serve.",
        ],
    },
    {
        title: "Dino Chicken Nuggets",
        _id: 2,
        imageUrl: "../../src/photos/Recipe-Photos/DinoNuggies.png",
        src: "../HTML/Recipes/DinoNuggies.html",
        methods: ["Air Fry", "Bake"],
        categories: ["Dinner", "Chicken"],
        time: "16 Min",

        ingredients: ["8 nuggets"],
        instructions: [
            "Preheat oven to 350F. Then insert the dino nuggies into the oven. After 8 minutes, flip them. Cook for 8 more minutes, then remove from oven and serve.",
            "Grab some sauces for dipping",
        ],
    },
    {
        title: "Breakfast Burritos",
        _id: 3,
        imageUrl: "../../src/photos/Recipe-Photos/Breakfast-Burrito.jpg",
        src: "../HTML/Recipes/BreakfastBurrito.html",

        methods: ["Saute"],
        categories: ["Breakfast", "eggs"],
        time: "1 hr",
        ingredients: [
            "4 Eggs",
            "4 Bacon Slics",
            "2.5 oz Peppers",
            "3 oz Onions",
            "Shredded Cheese",
            "2 tbs Heavy Cream",
            "3 Medium Flour Tortillas",
        ],
        instructions: [
            "First, we should prep our ingredients. Dice your Peppers and Onions, season them, and put in separate prepping bowls. Next crack your 4 eggs into a bowl, throw in some shredded cheese, and add a Tbs of heavy cream and whisk until melded.",
            "Place a pan over medium heat and add a little butter. Cook your 4 slices of bacon. Remove some of the bacon grease into a cup but leave enough to act as oil for our veggies.",
            "While the veggies sauté in that bacon grease, dice the bacon. Once veggies are cooked, set them aside. Finally add your eggs to the pan and season. Scramble them and season a bit more as you go. Once they are mostly cooked through, add in other ingredients and mix together. Pull off heat once eggs are done.",
            "Open your tortillas and lay down a hefty amount of shredded cheese on each. Distribute your burrito mix evenly to all 3, then add more cheese on top. Roll these up.",
            "Finally, set your oven to broil on medium(we want to make the outside crispy. Then pour some bacon grease back into the pan and fry the burritos in the bacon grease (it helps to do this with the fold down first to lock it in place). Flip the burritos to get all sides soaked in the grease and a little crispy. You can skip the oven, but I throw mine in until they are golden on both sides. Serve and enjoy.",
        ],
    },
    {
        title: "Mini Pizza Rolls",
        _id: 4,
        imageUrl: "../../src/photos/Recipe-Photos/miniPizzaRolls.JPG",
        src: "../HTML/Recipes/MiniPizzaRolls.html",

        methods: ["bake"],
        categories: ["Dinner", "Pepperoni"],
        time: "30 min",
        ingredients: [
            "Pillsbury Crescent Roll Sheet",
            "36 Pizza Pepperonis",
            "½ Cup Peppers",
            "½ Cup Onions",
            "Seasonings",
            "Shredded Cheese",
            "Pizza Sauce for Dipping",
        ],
        instructions: [
            "First, preheat the oven on bake to 350F and slice the Pillsbury sheet into 12 or more small triangles. They should have a 3 in base and a height of 4 inches. Lay them on foil slightly spread out. Season them with Italian seasoning, red pepper flakes, garlic powder, salt and pepper.",
            "Next sprinkle as many of your peppers and onions as you want on them. Next sprinkle a little bit of shredded cheese.",
            "Then, place 3-4 pepperoni on each one and top that with more shredded cheese. Roll these up into little croissants.",
            "Place them in the oven for about 10 minutes or until golden brown. Put your pizza sauce or any other dips into a serving bowl and enjoy.",
        ],
    },
    {
        title: "Pepperoni Stuffed Chicken",
        _id: 5,
        imageUrl: "../../src/photos/Recipe-Photos/PepperoniStuffedChicken.jpg",
        src: "../HTML/Recipes/PepperoniStuffedChicken.html",

        time: "1 hr",
        methods: ["Bake"],
        categories: ["Dinner", "Chicken"],

        ingredients: [
            "4 chicken breasts",
            "Pepperoni",
            "Onions",
            "Jalapenos",
            "Sliced cheese",
            "Sun dried tomato sauce",
            "Pasta of Choice",
        ],
        instructions: [
            "First, place your chicken breast in between two chopsticks. Make slices towards your cutting board slicing the chicken every inch. Place 2-3 pepperoni in each slice. You’ll want to place them on top and push in the middle, so it creates a sort of valley. ",

            "Next, thinly slice your onions, jalapenos, and cheese. Fill each pepperoni valley with these ingredients. Also coat the bottom of an oven dish with some of these ingredients. ",

            "Next, pour in some of your sauce into the bottom of your cooking dish and spread. You don’t need much there, just enough to have some flavor down there. Place the chicken over top and liberally pour the sauce over the chicken. You want to cover it and use most of the jar. ",

            "Finally place in the oven at 375 F for 25 minutes and check your chicken temperature. It may need more time, so leave it in until the internal temperature in a fatter part of the chicken is at 165. Remove the chicken from the juice and pour the remaining juice over pasta. Serve and enjoy.",
        ],
    },
    {
        title: "Flank Steak",
        imageUrl: "../../src/photos/Recipe-Photos/Flank-Steak.JPG",
        src: "",
        _id: 6,
        time: "1.5 hr",

        methods: ["Sous Vide"],
        categories: ["Dinner", "Steak"],
        ingredients: ["Flank Steak", "Seasoning"],
        instructions: [
            "Heat water to 135",
            "Season steak to preference and seal in a watertight bag with marinade if desired.",
            "Sous vide steak for 1 hour and 30 minutes for a rare flank.",
            "Remove steak from water and heat pan for sear as it rests for 10 minutes.",
            "Sear steak for a crust.",
            "Serve with roasted veggies or potatos.",
        ],
    },
    {
        title: "Cinnamon Swirl Sock it to Me Cake",
        _id: 7,
        imageUrl: "../../src/photos/Recipe-Photos/Cinnamon-Swirl-Cake.jpg",
        src: "",

        time: "1 hr",

        methods: "Baking",
        categories: ["Dessert", "Cake"],
        ingredients: [
            "1 Package Butter Yellow Cake",
            "2 Tbsp Brown Sugar",
            "2 Tsp Ground Cinnamon",
            " 4 Eggs",
            "1 Cup Sour Cream",
            "1/3 Cup Vegetable Oil",
            "1/4 Cup White Sugar",
            "1/4 Cup Water",
            "1 Cup Confectioners' Sugar",
            "2 Tbsp Milk",
        ],
        instructions: [
            "Preheat oven to 375 and grease a 10 inch bundt cake pan",
            "Mix 2 tbsp of each: brown sugar, cinnamon, and cake mix.",
            "Mix remaining cake mix with eggs, sour cream, oil, white sugar(not the confectioners'), and water. Beat well with an electric mixer.",
            "Pour layers of batter and the dry cinnamon sugar mix. Be sure to have the last layer be fully batter.",
            "Bake in oven until cooked through, about 35-45 minutes.",
            "While baking, make your icing. Combine your confectioners' sugar and milk and whisk together until smooth.",
            "After baking, let cool in pan for 20-30 minutes, then flip out and drizzle icing over the cake.",
        ],
    },
    {
        title: "Chicken Fried Rice",
        _id: 8,
        imageUrl: "../../src/photos/Recipe-Photos/Chicken-Fried-Rice.jpg",
        src: "",

        time: "1.2 hr",

        methods: ["saute", "sous vide"],
        categories: ["Dinner", "Chicken"],

        ingredients: [
            "1.5 Cup Leftover Rice",
            "4 chicken thighs",
            "1 cup Peppers",
            "1 cup Onions",
            ".5 cup Carrots",
            ".5 cup Baby Corns",
            "2 sprigs or 2 tsp dried Rosemary",
        ],
        instructions: [
            "First, the rice. Add oil to a small pot and place over low heat. Add 1 tbsp of butter, rosemary and other aromatics and allow to sauté for 3 minutes. Add 2 cups of chicken broth to the pot and bring to a boil. Next add in your 1.5 cups of washed jasmine rice. Stir as you bring it back to a boil. Then place a lid on the rice and drop the heat to a low simmer. Simmer rice for 13-15 minutes, and do not lift the lid. Once the rice seems to have absorbed our chicken broth: pull from heat, lift the lid, and stir. Allow it to rest until cools and place in fridge. You should cook the fried rice the next day, but if you want, you can chill it for as little as 30 minutes.",
            "Next, we cook the chicken. I typically use boneless, skinless thighs. First cut your chicken into small slices and marinade it for 30 minutes to 24 hours in desired spice mix along with some teriyaki sauce. Bring a wok over 7/10 heat and place oil in your pan. You will be using the same wok the whole time, so do not wash out the yummy bits. Quickly sauté your strips being sure not to overcrowd the pan (this may take several batches). When finished, dice the chicken to desired size for a rice dish, and set aside.",

            "Next, we prep the veggies. First dice the veggies into desired shape. Place the peppers and onions separate from the corn and carrots. Place a small amount of oil in the same wok over medium-high heat and add in the carrots and corn. Cover this and occasionally flick the wok to move the veggies around. You may need to scrape some of the chicken fond to incorporate it into your veggies. After 2 minutes, add in the onions and peppers and remove the cover. Cook to desired crunch level and place the veggies aside.",

            "Finally, we are ready to combine everything. Make sure you have some soy sauce and the teriyaki  sauce you used for the marinade. First, we bring our wok back up to high heat(9/10) with some oil. Add rice to wok and break up the clumps, stirring and flicking the wok as you go to make sure no rice burns. Once that is done, add veggies into the wok and incorporate. Begin adding some soy sauce and teriyaki sauce to taste. Once you have a desired salt and flavor level, add in your diced chicken and incorporate once more. Finally, serve.",
        ],
    },
    {
        title: "Hawaiian Sliders",
        _id: 9,
        imageUrl: "../../src/photos/Recipe-Photos/Hawaiian-Sliders.JPG",
        methods: ["saute", "grill"],
        categories: ["Dinner", "burgers", "beef", "tropical"],
        time: "45 Min",

        ingredients: [
            "1 Cup Ground Beef",
            "Hawaiian Rolls",
            "Lettuce",
            "Jalapeno Cheddar Jack Cheese",
            "1/3 Cup Pinapple",
            "1/3 Cup Jalepeno",
            "1/3 Cup Red Onion",
            "1 Tsp Teriyaki Sauce",
        ],
        instructions: [
            "Preheat grill to 375F. Slice fruit and veggies into small slices and divide your beef into 3 patties.",
            "Saute your fruit and veggies together until soft and toss in 1 tsp of teriyaki sauce ",
            "Season your beef and grill until nearly cooked through, flipping once.",
            "Place a pile of the pinapple slaw on each slider and place cheese on top to melt and hold in place.",
            "Place your buns in a hot pan to char slightly. Build your burgers, and enjoy.",
        ],
    },
    {
        title: "Pineapple Mango Salsa",
        _id: 10,
        imageUrl: "../../src/photos/Recipe-Photos/Mango-Salsa-Chicken.JPG",
        methods: ["saute", "grill"],
        categories: ["Dinner", "Chicken", "tropical"],
        time: "45 Min",

        ingredients: [
            "2 Cup Mango",
            "4 Cups Pineapple",
            "1.5 Cup Red Onions",
            "1 Cup Bell Peppers",
            "2Tbsp Jalepeno",
            "1/2 Orange Zested",
            "1/2 Lime Zested.",
        ],
        instructions: [
            "Dice all ingredients to desired size and combine in bowl.",
            "Add salt, pepper, and red pepper flakes to taste.",
            "Enjoy over chicken, rice, fish, or as a dip.",
        ],
    },
    {
        title: "Fried Eggs",
        _id: 11,
        imageUrl: "../../src/photos/Recipe-Photos/Fried-Eggs.JPG",
        methods: ["saute", "grill"],
        categories: ["Breakfast", "Eggs", "Easy"],
        time: "45 Min",

        ingredients: [
            "2-3 Eggs",
            "Garlic Italian Zest Seasoning.",
            "2-3 Slices Bacon",
            "Fruit",
        ],
        instructions: [
            "Saute bacon to desired crisp.",
            "Fry the eggs in the bacon grease.",
            "Slice some fruit, plate it all, and enjoy.",
        ],
    },
    {
        title: "Zesty Seafood Pasta",
        _id: 12,
        imageUrl: "../../src/photos/Recipe-Photos/Lemon Seafood Pasta.jpg",
        methods: ["saute", "grill"],
        categories: ["Breakfast", "Eggs", "Easy"],
        time: "45 Min",

        ingredients: [
            "1 Pound Linguini Noodles",
            "1 Lemon Zested",
            "1 Chicken Bouillon Cube",
            "1/2 Pound Shrimp",
            "1/2 Pound Scallops",
            "1/4 Pound Blue Crab",
            "1 Shallot Diced",
            "1 Cup Yellow Onions Sliced",
            "1/2 Cup Bell Peppers Diced",
            "3 Cloves Garlic Minced",
            "3/4 Cup Dry White Wine",
            "1 Cup Freshly Grated Parmesan",
            "1/4 Cup Chopped Parsley",
        ],
        instructions: [
            "Prepare your seafood and season with salt and pepper and other desired spice.",
            "If crab is not prepared, boil and break crab down into small pieces.",
            "Add 1 Tbsp of butter to skillet over medium heat and cook shrimp and scallops for 2 minutes per side. Transfer to a plate and set aside.",
            "Add 3 Tbsp of butter to skillet and add shallots and other veggies. Cook for 2-3 minutes. Add garlic and cook for 30 seconds. Add wine and bring to a simmer, cooking for a few minutes. ",
            "Stir 1 teaspoon cornstarch into the cream. Add cream mixture, bouillon, and ¾ cup of the parmesan to the pan and cook until sauce has slightly thickened. Taste and season with salt and pepper, if needed.",
            "Add pasta and lemon zest and toss to coat. Add seafood. Garnish with parsley and remaining parmesan. Enjoy.",
        ],
    },
];
export default RecipesData;
